language: java
dist: trusty
jdk:
- oraclejdk8
addons:
    sonarcloud:
        organization: "cafecanudo-github"
        token:
            secure: $SONAR_TOKEN
script:
- sonar-scanner
after_success:
- mvn clean test jacoco:report