server:
    port: 8062

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8061/eureka/
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            -   id: user-service
                uri: lb://user-service
                predicates:
                - Path=/user/**
                filters:
                - RewritePath=/user/(?<path>.*), /user/$\{path}