server:
    port: 9010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8061/eureka/
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            -   id: veiculo-service
                uri: lb://veiculo-service
                predicates:
                - Path=/veiculo/**
                filters:
                - AddResponseHeader=Access-Control-Allow-Origin, *
                - RewritePath=/veiculo/(?<path>.*), /veiculo/$\{path}
            -   id: produto-service
                uri: lb://produto-service
                predicates:
                - Path=/produto/**
                filters:
                - AddResponseHeader=Access-Control-Allow-Origin, *
                - RewritePath=/produto/(?<path>.*), /produto/$\{path}
            -   id: transporte-service
                uri: lb://transporte-service
                predicates:
                - Path=/transporte/**
                filters:
                - AddResponseHeader=Access-Control-Allow-Origin, *
                - RewritePath=/transporte/(?<path>.*), /transporte/$\{path}
            -   id: transporte-service
                uri: lb://transporte-service
                predicates:
                - Path=/via/**
                filters:
                - AddResponseHeader=Access-Control-Allow-Origin, *
                - RewritePath=/via/(?<path>.*), /via/$\{path}